name: flutter_catalog
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_html: ^3.0.0
  flutter_svg: ^2.0.17
  html: ^0.15.5+1
  http: ^1.3.0
  material_symbols_icons: ^4.2801.1
  path: ^1.9.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  analyzer: ^7.4.5

flutter:
  uses-material-design: true

  assets: 
    - assets/logos/
